server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      minimum-idle: 8
      maximum-pool-size: 15
  redis:
    port: 6379
    host: 182.92.100.82
    password: 123456
    jedis:
      pool:
        max-active: 8
        min-idle: 1


mybatis:
  type-aliases-package: com.neuedu.pojo
logging:
  level:
    com.neuedu.dao: debug
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 182.92.100.82:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    max_idle_per_key: 5
